# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/gomod"
    schedule:
      interval: "daily"
    # auto-merge config for Go modules
    auto-merge-settings:
      enabled: true
      require-all-status-checks: true
      merge-strategy: "squash"
      versioning-strategy: "auto"
      # only allow auto-merge for minor and patch updates
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # auto-merge config for npm packages
    auto-merge-settings:
      enabled: true
      require-all-status-checks: true
      merge-strategy: "squash"
      versioning-strategy: "auto"
      # only allow auto-merge for minor and patch updates
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]

