name: Build and Test 

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      
      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Build and test Go backend 
        run: |
          cd go-server 
          docker build -t vis-service-go:latest . 
          docker run --rm vis-service-go:latest go test -v ./...

      - name: Build and test Node.js frontend
        run : |
          docker build -t vis-service-node:latest .
          docker run --rm vis-service-node:latest npm test -- --watchAll=false --passWithNoTests