name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    auto-merge:    
        runs-on: ubuntu-latest 
        if: github.actor == 'dependabot[bot]'
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Dependabot metadata
              id: metdata 
              uses: dependabot/fetch-metadata@v1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Enable auto-merge for minor and patch updates
              if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
              run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash "$PR_URL"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                PR_URL: ${{ github.event.pull_request.html_url }}